export const USERNAME_DIALOG_HEIGHT = '116px';
export const USERNAME_DIALOG_WIDTH = '480px';
export const USERNAME_DIALOG_ENTER_ANIMATION_DURATION = '250ms';
export const USERNAME_DIALOG_EXIT_ANIMATION_DURATION = '250ms';
