export const THEME_FIXED_PROPERTIES: Record<string, string> = {
  '--font-size': '14px',
  '--line-height': '21px',
  '--title-font-size': '20px',
  '--title-line-height': '28px',
  '--letter-spacing': '0.24px',
  '--padding': '8px',
  '--toolbar-height': '36px',
  '--header-height': '32px',
  '--footer-height': '32px',
  '--panel-width': '320px',
  '--border-radius': '10px',
  '--dark-text-color': 'var(--gray-a20)',
  '--dark-link-color': 'var(--gray-a0)',
  '--dark-border-color': 'var(--gray-a85)',
  '--dark-input-border-color': 'var(--gray-a75)',
  '--light-text-color': 'var(--gray-a80)',
  '--light-link-color': 'var(--gray-a100)',
  '--light-border-color': 'var(--gray-a15)',
  '--light-input-border-color': 'var(--gray-a25)',
};
